### ISSUE TITLE
Initial load time for the UI is slow

### ISSUE THREAD

**Issue by markemeis** [CATechnologiesTest/yipee#14]
The initial load of the application in the browser is pretty slow.  Is there a way to reduce the size of scripts.js, vendor.js, main.js as it looks like these constitute the majority of the load time.

**Comment by bl8nr** [comment]
@markemeis @D3nn @jd3quist @andrewcopley 

seems like the build is building non-minified version of the app. Tried to change the npm build-prod script so that its building minified code and using AOT but upon spinning locally in docker noticed the env still wasn't serving minified and optimized code despite all the /dist code being minified. @D3nn im wondering if this could be related to the docker build file. Does the docker build file build the app itself?

**Comment by D3nn** [comment]
The current Dockerfile runs `npm run test-prod` in the build stage, which you altered to additionally run `ng build --prod`.  Assuming that produces minified code, the minified code should be copied into the nginx image:
```
COPY --from=builder /app/dist ${HTML_DEST}
```

This probably is NOT in the yipee/yipee repo as it didn't make the cutoff for merge.
