### ISSUE TITLE
Save the layout of a model within the model and use it on re-import

### ISSUE THREAD

**Issue by markemeis** [CATechnologiesTest/yipee#19]
When a model is created and downloaded we want the layout information contained in the download.  Then on import, if layout information is present, use it to layout the model instead of the auto layout.

The idea is to use one annotation tied to a deployment within the model.  This is necessary as the model has objects that don't have K8s objects, e.g. host path volumes.

**Comment by jd3quist** [comment]
We decided against annotations since a change to an annotation can result in a redeployment of the containing object.  Seems bad to re-deploy a controller due to a modified yipee layout.

Instead, layout data is stored in a "special" ConfigMap named "yipee-layout-data".  The ConfigMap is included in a download and processed/removed on import.
